name: carbonshadowtracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  flutter_animate: ^4.5.0
  confetti: ^0.7.0
  model_viewer_plus: ^1.7.0
  google_generative_ai: ^0.4.6 
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  image_picker: ^1.1.1
  http: ^1.6.0
  camera: ^0.10.5
  google_mlkit_object_detection: ^0.15.0
  google_mlkit_commons: ^0.11.0
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # ðŸ‘‡ 2 spaces indentation
  assets:
    # ðŸ‘‡ 4 spaces indentation
    - assets/model.glb
dependency_overrides:
  google_generative_ai: ^0.4.6